enum BaseTrait {
    ancientFoeDemons = 'ancientFoeDemons',
    arcaneAcuity = 'arcaneAcuity',
    arcaneAffinity = 'arcaneAffinity',
    corneredFury = 'corneredFury',
    darkvision60 = 'darkvision60',
    defensiveTrainingDemons = 'defensiveTrainingDemons',
    elvenMagic = 'elvenMagic',
    elvenImmunities = 'elvenImmunities',
    energyDrainResistance = 'energyDrainResistance',
    eternalHope = 'eternalHope',
    expansiveMind = 'expansiveMind',
    gnomeMagic = 'gnomeMagic',
    greed = 'greed',
    gregarious = 'gregarious',
    gryphonAffinity = 'gryphonAffinity',
    hardy = 'hardy',
    healthy = 'healthy',
    illusionResistance = 'illusionResistance',
    keenSenses = 'keenSenses',
    lightBringer = 'lightBringer',
    lowLightVision = 'lowLightVision',
    lucky = 'lucky',
    mountaineer = 'mountaineer',
    nimbleFingers = 'nimbleFingers',
    quickness = 'quickness',
    stability = 'stability',
    stonecunning = 'stonecunning',
    undeadSaves = 'undeadSaves',
    unencumbered = 'unencumbered',
}

export { BaseTrait };
