enum ExoticWeaponProficiency {
    kama = 'kama',
    nunchaku = 'nunchaku',
    sai = 'sai',
    siangham = 'siangham',
    swordBastard = 'swordBastard',
    axeWarDwarven = 'axeWarDwarven',
    whip = 'whip',
    axeDoubleOrc = 'axeDoubleOrc',
    chainSpiked = 'chainSpiked',
    bladeCurveElven = 'bladeCurveElven',
    flailDire = 'flailDire',
    hammerHookedGnome = 'hammerHookedGnome',
    swordTwoBladed = 'swordTwoBladed',
    urgoshDwarven = 'urgoshDwarven',
    bolas = 'bolas',
    crossbowHand = 'crossbowHand',
    crossbowRepeatingHeavy = 'crossbowRepeatingHeavy',
    crossbowRepeatingLight = 'crossbowRepeatingLight',
    net = 'net',
    shuriken = 'shuriken',
    slingStaffHalfling = 'slingStaffHalfling',
}

export { ExoticWeaponProficiency };
