enum MartialWeaponProficiency {
    axeThrown = 'axeThrown',
    hammerLight = 'hammerLight',
    axeHand = 'axeHand',
    kukri = 'kukri',
    pickLight = 'pickLight',
    sap = 'sap',
    shieldLight = 'shieldLight',
    starKnife = 'starKnife',
    swordShort = 'swordShort',
    axeBattle = 'axeBattle',
    flail = 'flail',
    swordLong = 'swordLong',
    pickHeavy = 'pickHeavy',
    rapier = 'rapier',
    scimitar = 'scimitar',
    shieldHeavy = 'shieldHeavy',
    trident = 'trident',
    warhammer = 'warhammer',
    falchion = 'falchion',
    glaive = 'glaive',
    axeGreat = 'axeGreat',
    clubGreat = 'clubGreat',
    flailHeavy = 'flailHeavy',
    swordGreat = 'swordGreat',
    guisarme = 'guisarme',
    halberd = 'halberd',
    lance = 'lance',
    ranseur = 'ranseur',
    scythe = 'scythe',
    bowLong = 'bowLong',
    bowLongComposite = 'bowLongComposite',
    bowShort = 'bowShort',
    bowShortComposite = 'bowShortComposite',
}

export { MartialWeaponProficiency };
